<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>38efd21e-dcb3-4a24-819f-4905abb3e957</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/p/a[contains(text(),'Login')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.login-link > div > p > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Contentplaceholder1_T99701C38008_Col02 >> internal:role=link[name=&quot;Login&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>743d35f7-f58e-4308-83f2-336dcae8c9d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://intdev01.hastingsmutual.com/Authentication/Login?ReturnUrl=https://webdev.hastingsmutual.com/userauthorized</value>
      <webElementGuid>db660cd1-6a1b-4208-bf59-17101ce2dcaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>1d34bb18-4d4a-43e9-ab82-71fb721ac475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Contentplaceholder1_T99701C38008_Col02&quot;)/div[@class=&quot;login-link&quot;]/div[1]/p[1]/a[1]</value>
      <webElementGuid>6e8b640c-e736-410f-b2ac-942aebe2fad2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Contentplaceholder1_T99701C38008_Col02']/div[2]/div/p/a</value>
      <webElementGuid>99a9c45e-16a9-40cc-8ec6-5e31d262ab48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>49442db7-0f10-4a3b-9c43-6ebe53527706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make A Payment'])[1]/following::a[1]</value>
      <webElementGuid>1fa180db-3b8c-4869-8d67-168190e95d46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report a Claim'])[1]/following::a[2]</value>
      <webElementGuid>5b9a57d5-c908-4422-be7e-c89dce250f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Careers'])[1]/preceding::a[1]</value>
      <webElementGuid>afa5fad5-0ae7-456a-9bdf-f8582129ad72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[2]/preceding::a[2]</value>
      <webElementGuid>6784c917-56a5-4464-b04d-579714cf0f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://intdev01.hastingsmutual.com/Authentication/Login?ReturnUrl=https://webdev.hastingsmutual.com/userauthorized')])[2]</value>
      <webElementGuid>4b710ec8-62f4-40b4-8f63-0fe20afeff02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p/a</value>
      <webElementGuid>8dddbf91-ecef-4a04-9e5a-4ca43181df6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://intdev01.hastingsmutual.com/Authentication/Login?ReturnUrl=https://webdev.hastingsmutual.com/userauthorized' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>be2fa5f8-7f54-404e-914a-ee2d930814d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
